name:  test_client
description:  A sample application

dependencies:
  xml:
    git: https://github.com/prujohn/dart-xml.git
  presentation:
    git: https://github.com/CatalystItLabs/presentation.dart
  intl:
    sdk: intl