name:  test_client
description:  A sample application

dependencies:
  xml:
    git: git://github.com/prujohn/dart-xml.git
  presentation:
    git: git://github.com/CatalystITLabs/presentation.dart.git
  intl:
    sdk: intl