name:  test_client
description:  A sample application

dependencies:
  xml:
    git: git://github.com/CatalystITLabs/dart-xml.git
  presentation:
    git: git://github.com/CatalystITLabs/presentation.dart.git
  intl:
    git: git://github.com/CatalystITLabs/intl
  crimsonhttp: 
    git: git://github.com/CatalystITLabs/CrimsonHttp
  mongo_dart: 
    git: git://github.com/vadimtsushko/mongo_dart