name:  test_client
description:  A sample application

dependencies:
  xml:
    git: git://github.com/prujohn/dart-xml.git
  presentation:
    git: git://github.com/CatalystITLabs/presentation.dart.git
  intl:
    sdk: intl

  crimsonhttp: 
    git: git://github.com/chrisbu/CrimsonHttp
  mongo_dart: 
    git: git://github.com/vadimtsushko/mongo_dart
    