name:  test_client
description:  A sample application

dependencies:
  intl:
    git: git://github.com/CatalystITLabs/intl.git
  xml:
    git: git://github.com/CatalystITLabs/dart-xml.git
  presentation:
    git: git://github.com/CatalystITLabs/presentation.dart.git
  crimsonhttp:
    git: git://github.com/CatalystITLabs/CrimsonHttp.git
  mongo_dart:
    git: git://github.com/vadimtsushko/mongo_dart.git
    